name: Generate KEYSTORE_BASE64
on: workflow_dispatch
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make Base64
        run: |
          if [ -f "release.keystore" ]; then
            echo "release.keystore mil gaya!"
            base64 -w 0 release.keystore > b64.txt
          else
            echo "Naya keystore bana raha hu..."
            keytool -genkey -v -keystore release.keystore -alias ${{ secrets.KEY_ALIAS }} -keyalg RSA -keysize 2048 -validity 10000 -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} -dname "CN=Merge, OU=Dev, O=Kesarmal, L=Delhi, S=Delhi, C=IN"
            base64 -w 0 release.keystore > b64.txt
          fi
          echo "==== COPY THIS FULL LINE ===="
          cat b64.txt
          echo ""
          echo "==== END COPY ===="
